platform :ios, '7.0'
pod 'UIImage-Categories'
pod 'BBBadgeBarButtonItem'
pod 'Reachability'
pod 'SwipeView'
pod 'pop', :git => 'https://github.com/facebook/pop'
pod 'MBProgressHUD'
pod 'objectiveflickr'
pod 'JSQMessagesViewController'
pod 'Mapbox-iOS-SDK', :git => 'https://github.com/mapbox/mapbox-ios-sdk', :branch => 'develop'
