platform :ios, '7.0'
pod 'UIImage-Categories'
pod 'BBBadgeBarButtonItem'
pod 'Lookback'
pod 'Reachability'
pod 'SwipeView'
pod 'pop', '~> 1.0'
pod 'MBProgressHUD'
pod 'objectiveflickr'
pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController', :branch => 'develop'
pod 'Mapbox', :git => 'https://github.com/mapbox/mapbox-ios-sdk', :branch => 'develop'
